Use Ruby v3.0
```
Run gem install bundler
Successfully installed bundler-2.3.4
1 gem installed
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Fetching gem metadata from https://rubygems.org/.........
nokogiri-1.12.5-x86_64-linux requires ruby version < 3.1.dev, >= 2.5, which is
incompatible with the current version, ruby 3.1.0p0
Error: Process completed with exit code 5.
```